# Generated by Django 5.1.3 on 2025-01-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default_recipe_image.png', null=True, upload_to='recipe_images'),
        ),
    ]
